/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import { jsonColumn } from '#utils/orm'
import type {
  MetaFormat,
  MetaSource,
  SyncJobType,
  SyncStatus,
  UsageEntry,
  SpreadEntry,
} from '#services/meta/meta_types'

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActivated', 'isGuest', 'password', 'provider', 'providerId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActivated: boolean
  @column()
  declare isGuest: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare provider: string | null
  @column()
  declare providerId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ActivationTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'updatedAt', 'userId'] as const
  $columns = ActivationTokenSchema.$columns
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class ResetPasswordTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'updatedAt', 'userId'] as const
  $columns = ResetPasswordTokenSchema.$columns
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class ProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'format', 'id', 'level', 'objective', 'style', 'updatedAt', 'userId'] as const
  $columns = ProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare format: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: string
  @column()
  declare objective: string
  @column()
  declare style: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TeamSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'format', 'id', 'isPublic', 'likesCount', 'name', 'regulation', 'style', 'updatedAt', 'userId'] as const
  $columns = TeamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare format: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPublic: boolean
  @column()
  declare likesCount: number
  @column()
  declare name: string
  @column()
  declare regulation: string | null
  @column()
  declare style: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TeamSlotSchema extends BaseModel {
  static $columns = ['ability', 'createdAt', 'id', 'item', 'move1', 'move2', 'move3', 'move4', 'nature', 'nickname', 'pokemonId', 'slotIndex', 'spAtk', 'spDef', 'spHp', 'spSpa', 'spSpd', 'spSpe', 'teamId', 'updatedAt'] as const
  $columns = TeamSlotSchema.$columns
  @column()
  declare ability: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare item: string | null
  @column()
  declare move1: string | null
  @column()
  declare move2: string | null
  @column()
  declare move3: string | null
  @column()
  declare move4: string | null
  @column()
  declare nature: string
  @column()
  declare nickname: string | null
  @column()
  declare pokemonId: number
  @column()
  declare slotIndex: number
  @column()
  declare spAtk: number
  @column()
  declare spDef: number
  @column()
  declare spHp: number
  @column()
  declare spSpa: number
  @column()
  declare spSpd: number
  @column()
  declare spSpe: number
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommentSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'teamId', 'updatedAt', 'userId'] as const
  $columns = CommentSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CommentReportSchema extends BaseModel {
  static $columns = ['commentId', 'createdAt', 'id', 'reason', 'reporterId'] as const
  $columns = CommentReportSchema.$columns
  @column()
  declare commentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string
  @column()
  declare reporterId: number
}

export class UserBlockSchema extends BaseModel {
  static $columns = ['blockedId', 'blockerId', 'createdAt', 'id'] as const
  $columns = UserBlockSchema.$columns
  @column()
  declare blockedId: number
  @column()
  declare blockerId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'plan', 'revenuecatUserId', 'status', 'updatedAt', 'userId'] as const
  $columns = SubscriptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare plan: string
  @column()
  declare revenuecatUserId: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PokemonDataSchema extends BaseModel {
  static $columns = ['abilities', 'baseAtk', 'baseDef', 'baseHp', 'baseSpa', 'baseSpd', 'baseSpe', 'id', 'inRegMa', 'isMega', 'megaOf', 'moves', 'nameFr', 'nameEn', 'regulationNotes', 'spriteUrl', 'type1', 'type2', 'updatedAt'] as const
  $columns = PokemonDataSchema.$columns
  @column({
    prepare: (value: string[]) => JSON.stringify(value ?? []),
    consume: (value: unknown) => (typeof value === 'string' ? JSON.parse(value) : (value ?? [])),
  })
  declare abilities: string[]
  @column()
  declare baseAtk: number
  @column()
  declare baseDef: number
  @column()
  declare baseHp: number
  @column()
  declare baseSpa: number
  @column()
  declare baseSpd: number
  @column()
  declare baseSpe: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inRegMa: boolean
  @column()
  declare isMega: boolean
  @column()
  declare megaOf: number | null
  @column({
    prepare: (value: number[]) => JSON.stringify(value ?? []),
    consume: (value: unknown) => (typeof value === 'string' ? JSON.parse(value) : (value ?? [])),
  })
  declare moves: number[]
  @column()
  declare nameFr: string
  @column()
  declare nameEn: string
  @column()
  declare regulationNotes: string | null
  @column()
  declare spriteUrl: string
  @column()
  declare type1: string
  @column()
  declare type2: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemDataSchema extends BaseModel {
  static $columns = ['id', 'nameFr', 'nameEn', 'slug', 'spriteUrl'] as const
  $columns = ItemDataSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nameFr: string
  @column()
  declare nameEn: string
  @column()
  declare slug: string
  @column()
  declare spriteUrl: string
}

export class MoveDataSchema extends BaseModel {
  static $columns = ['accuracy', 'category', 'descriptionFr', 'id', 'nameFr', 'nameEn', 'power', 'pp', 'type'] as const
  $columns = MoveDataSchema.$columns
  @column()
  declare accuracy: number | null
  @column()
  declare category: string
  @column()
  declare descriptionFr: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nameFr: string
  @column()
  declare nameEn: string
  @column()
  declare power: number | null
  @column()
  declare pp: number
  @column()
  declare type: string
}

export class TeamLikeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'teamId', 'userId'] as const
  $columns = TeamLikeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare teamId: number
  @column()
  declare userId: number
}

export class MetaCacheSchema extends BaseModel {
  static $columns = [
    'id', 'pokemonName', 'format', 'source', 'regulation', 'rank', 'usageRate',
    'winRate', 'moves', 'items', 'abilities', 'teammates', 'spreads', 'rawData',
    'fetchedAt', 'createdAt', 'updatedAt',
  ] as const
  $columns = MetaCacheSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare pokemonName: string
  @column()
  declare format: MetaFormat
  @column()
  declare source: MetaSource
  @column()
  declare regulation: string
  @column()
  declare rank: number | null
  @column()
  declare usageRate: number | null
  @column()
  declare winRate: number | null
  @jsonColumn<UsageEntry[]>([])
  declare moves: UsageEntry[]
  @jsonColumn<UsageEntry[]>([])
  declare items: UsageEntry[]
  @jsonColumn<UsageEntry[]>([])
  declare abilities: UsageEntry[]
  @jsonColumn<UsageEntry[]>([])
  declare teammates: UsageEntry[]
  @jsonColumn<SpreadEntry[]>([])
  declare spreads: SpreadEntry[]
  @column()
  declare rawData: string | null
  @column.dateTime()
  declare fetchedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PokemonRosterSchema extends BaseModel {
  static $columns = [
    'id', 'pokemonId', 'slug', 'nameEn', 'nameFr', 'form', 'baseFormId', 'type1',
    'type2', 'baseHp', 'baseAtk', 'baseDef', 'baseSpa', 'baseSpd', 'baseSpe',
    'isMega', 'isAvailable', 'spriteUrl', 'regulation', 'rawData', 'syncedAt',
    'createdAt', 'updatedAt',
  ] as const
  $columns = PokemonRosterSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare pokemonId: number
  @column()
  declare slug: string | null
  @column()
  declare nameEn: string
  @column()
  declare nameFr: string | null
  @column()
  declare form: string | null
  @column()
  declare baseFormId: number | null
  @column()
  declare type1: string | null
  @column()
  declare type2: string | null
  @column()
  declare baseHp: number | null
  @column()
  declare baseAtk: number | null
  @column()
  declare baseDef: number | null
  @column()
  declare baseSpa: number | null
  @column()
  declare baseSpd: number | null
  @column()
  declare baseSpe: number | null
  @column()
  declare isMega: boolean
  @column()
  declare isAvailable: boolean
  @column()
  declare spriteUrl: string | null
  @column()
  declare regulation: string
  @jsonColumn<Record<string, unknown>>({})
  declare rawData: Record<string, unknown>
  @column.dateTime()
  declare syncedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SyncLogSchema extends BaseModel {
  static $columns = [
    'id', 'jobType', 'status', 'recordsUpserted', 'errorMessage', 'durationMs',
    'triggeredBy', 'createdAt',
  ] as const
  $columns = SyncLogSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare jobType: SyncJobType
  @column()
  declare status: SyncStatus
  @column()
  declare recordsUpserted: number
  @column()
  declare errorMessage: string | null
  @column()
  declare durationMs: number | null
  @column()
  declare triggeredBy: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}
