/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  activation: {
    Activations: () => import('#controllers/activation/activations_controller'),
  },
  Admin: () => import('#controllers/admin_controller'),
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
    AuthFacebook: () => import('#controllers/auth/auth_facebook_controller'),
    AuthGoogle: () => import('#controllers/auth/auth_google_controller'),
  },
  Comment: () => import('#controllers/comment_controller'),
  CommentReports: () => import('#controllers/comment_reports_controller'),
  Community: () => import('#controllers/community_controller'),
  Item: () => import('#controllers/item_controller'),
  Meta: () => import('#controllers/meta_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  passwordReset: {
    PasswordResets: () => import('#controllers/password_reset/password_resets_controller'),
  },
  Pokemon: () => import('#controllers/pokemon_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Roster: () => import('#controllers/roster_controller'),
  Session: () => import('#controllers/session_controller'),
  Subscription: () => import('#controllers/subscription_controller'),
  Sync: () => import('#controllers/sync_controller'),
  Team: () => import('#controllers/team_controller'),
  UserBlocks: () => import('#controllers/user_blocks_controller'),
  Webhook: () => import('#controllers/webhook_controller'),
}
